version: '3.7'

services:
  php8:
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/src
      - ./public:/var/www/public
      - ./templates:/var/www/templates
      - ./vendor:/var/www/vendor
      - ./config:/var/www/config
      - ./bin:/var/www/bin
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./.env:/var/www/.env
    environment:
      DATABASE_URL: mysql://root:symfony@database/chargingDA?serverVersion=8
    depends_on:
      - database
    networks:
      - symfony

  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: chargingDA
      MYSQL_USER: chargingDA
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "33060:3306"
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: symfony
    ports:
      - "8080:80"
    networks:
      - symfony

volumes:
  db-data:

networks:
  symfony:
    driver: bridge